name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  claude-code-review:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request && 
       contains(github.event.comment.body, '@claude-code'))
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          # Use the OAuth token for authentication
          claude_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
      - name: Run Claude Code Review
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Automatic review on PR events
            claude-code review \
              --pr ${{ github.event.pull_request.number }} \
              --base ${{ github.event.pull_request.base.sha }} \
              --head ${{ github.event.pull_request.head.sha }}
          else
            # Manual review triggered by comment
            claude-code review \
              --pr ${{ github.event.issue.number }} \
              --comment "${{ github.event.comment.body }}"
          fi